### ISSUE TITLE
New release on chrome web store

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-extender#1]
https://chrome.google.com/webstore/detail/o2r-badge-integrator/fhhfncpkfohlhphlcgpkbpialfhkmbil

- [x] add screenshots (1280x800 or 640x400)
- [x] change name to "Open Reproducible Research Extender"
- rename local folder to not use capitals in "o2r", see https://stackoverflow.com/questions/11183788/in-a-git-repository-how-to-properly-rename-a-directory

**Comment by LukasLohoff** [comment]
Done!
