### ISSUE TITLE
Add left-click action to extension button

### ISSUE THREAD

**Issue by LukasLohoff** [o2r-project/o2r-extender#4]
> When a user left-clicks on the icon in Chrome, nothing happens.
> 
> Why not open the menu, just as with a right click?
> Or show the number of retrieved badges for the current page?
> 
> Other ideas what could be shown welcome.

Moved from https://github.com/o2r-project/o2r-badger/issues/3.

**Comment by nuest** [comment]
@LukasLohoff What's your take on this?

**Comment by LukasLohoff** [comment]
With #3 I added a left-click menu with the options "disable/enable", "Help" and "About". The "help" and "about" options open a new tab with the local help.html from the study project.

Right now it looks like this:
![image](https://user-images.githubusercontent.com/5795523/27035303-1aba97ca-4f81-11e7-8ef7-4f6d5ad91e5a.png)

**Comment by nuest** [comment]
I cannot confirm this works for me. When I click disable, the icon does not change and badges are still loaded. When I left-click again the button still says "Disable".

I'm using Chromium "Version 58.0.3029.110 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)".

Can you add the same functionality in the settings page (afair we said it should be there, too), just to be sure it is not an issue with the pop-up kind of menu?

**Comment by LukasLohoff** [comment]
![image](https://user-images.githubusercontent.com/5795523/27092191-d92ad8d2-5062-11e7-958d-865b47d78127.png)

Now the text should be a bit bigger and enabling and disabling should work again.
